const section = (title: string, body: string) => `<h2>${title}</h2>${body}`;

export const legalPolicies = {
  terms: `<h1 style="text-align:center">Terms of Service</h1><p style="text-align:center"><strong>Effective Date:</strong> 11.01.2026</p>
${section("1. Acceptance of Terms", `<p>By accessing or using our website, Discord server, or any related services (collectively, the “Services”), you agree to be bound by these Terms of Service and all applicable laws and regulations.</p><p>If you do not agree to these Terms, you must not access or use our Services.</p>`)}
${section("2. Use of Services", `<p>You agree to use our Services only for lawful purposes and in compliance with all applicable laws and regulations.</p><p>You must not attempt to disrupt, interfere with, misuse, reverse-engineer, or otherwise alter any part of our Services, systems, or infrastructure.</p>`)}
${section("3. Accounts", `<p>If you create an account, you are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately if you suspect any unauthorized access or use of your account.</p>`)}
${section("4. Purchases and Pricing", `<p>All purchases are subject to the pricing displayed at the time of purchase. You agree to provide accurate and complete payment information and to complete transactions promptly.</p>`)}
${section("5. Refunds", `<p>Refunds are not guaranteed and are handled in accordance with our <strong>Refund Policy</strong>. By making a purchase, you acknowledge that refunds may be denied at our sole discretion.</p>`)}
${section("6. Compatibility Responsibility", `<p>It is your responsibility to ensure that your system meets all stated requirements before making a purchase. We do not guarantee compatibility with all systems, and incompatibility issues are generally not eligible for refunds.</p>`)}
${section("7. Chargebacks", `<p>Initiating a chargeback or payment dispute without first contacting our support may result in the suspension or termination of your account and access to our Services.</p>`)}
${section("8. Intellectual Property", `<p>All content, software, designs, and materials associated with our Services are our intellectual property and are protected by applicable copyright and trademark laws. You may not copy, modify, distribute, or use any of our intellectual property without prior written consent.</p>`)}
${section("9. Limitation of Liability", `<p>To the fullest extent permitted by law, we shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use our Services.</p>`)}
${section("10. Termination", `<p>We reserve the right to suspend or terminate your account or access to the Services at any time, with or without notice, for any reason, including violations of these Terms.</p>`)}
${section("11. Modifications", `<p>We reserve the right to modify these Terms at any time. Continued use of the Services after changes are posted constitutes acceptance of the revised Terms.</p>`)}
${section("12. Contact", `<p>If you have any questions regarding these Terms of Service, please contact us via our official Discord server.</p>`)}
${section("13. Product Duration", `<p>Products are provided for the duration stated at the time of purchase. Lifetime access means you can use the product for as long as that product remains active and in service. If we replace, discontinue, or change a product, we may offer compensation or an alternative product where appropriate. “Lifetime” does not guarantee that a product or service will operate indefinitely.</p>`)}`,
  privacy: `<h1 style="text-align:center">Privacy Policy</h1><p style="text-align:center"><strong>Effective Date:</strong> 11.01.2026</p>
${section("1. Data Collection and Use", `<p>We respect your privacy and are committed to protecting your personal information. Any data collected is used solely to operate our Services, improve functionality, and communicate with users.</p>`)}
${section("2. Information Sharing", `<p>We do not sell, rent, or share your personal or sensitive information with third parties. Access to user data is strictly limited to authorized personnel for legitimate business purposes.</p>`)}
${section("3. Security", `<p>We implement industry-standard security measures to protect your information from unauthorized access, alteration, or disclosure. However, no system can be guaranteed to be completely secure.</p>`)}
${section("4. Your Rights", `<p>You have the right to request access to the data we hold about you and request correction or deletion of your personal data. To exercise these rights, please contact us via our official Discord server.</p>`)}
${section("5. Changes to This Policy", `<p>We reserve the right to update this Privacy Policy at any time. Any changes will be posted on this page with an updated effective date.</p>`)}
${section("6. Contact", `<p>For any questions regarding privacy, please contact us through our official Discord server.</p>`)}`,
  refund: `<h1 style="text-align:center">Refund Policy</h1><p style="text-align:center"><strong>Effective Date:</strong> 11.01.2026</p>
${section("1. Overview", `<p>We strive to provide high-quality products and services. Refunds are evaluated on a <strong>case-by-case basis</strong> and are granted <strong>at our sole discretion</strong>.</p>`)}
${section("2. Eligibility for Refunds", `<ul><li>Verified technical issues that prevent the software from functioning and cannot be resolved</li><li>Undelivered products or services beyond the stated delivery timeframe</li><li>Proven unauthorized or fraudulent purchases</li></ul>`)}
${section("3. Non-Refundable Situations", `<p>Refunds will not be provided for violations of our Terms of Service, unsupported or incompatible systems, personal circumstances or change of mind, compatibility issues despite meeting stated requirements, or account suspension or termination due to rule violations.</p>`)}
${section("4. Refund Process", `<ol><li>Contact our support team via the official Discord server</li><li>Provide your order details and a clear explanation of the issue</li><li>Allow up to <strong>5 business days</strong> for review and response</li></ol>`)}
${section("5. Important Notes", `<ul><li>Approved refunds will be issued to the original payment method</li><li>Partial refunds may be issued depending on usage and circumstances</li></ul>`)}
${section("6. Changes to This Policy", `<p>We reserve the right to modify this Refund Policy at any time. Changes will be posted with an updated effective date.</p>`)}
${section("7. Contact", `<p>For any questions regarding refunds, please contact us through our official Discord server.</p>`)}`,
} as const;
